# Generated by Django 6.0.5 on 2026-06-10 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0006_tiporefeicao_alter_configreserva_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiporefeicao',
            name='horario_inicio_consumo',
        ),
    ]
