# Generated by Django 6.0.5 on 2026-06-10 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0008_notificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='janelareserva',
            name='tipo_refeicao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='janela', to='administrativo.tiporefeicao'),
        ),
        migrations.AlterField(
            model_name='strike',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
