# Generated by Django 6.0.5 on 2026-07-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0012_tiporefeicao_horario_fim_consumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='janelareserva',
            name='minutos_pre_reserva',
            field=models.IntegerField(default=30, verbose_name='Prazo de confirmação da pré-reserva (minutos)'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dias_contraturno',
            field=models.JSONField(blank=True, default=list, help_text='Dias da semana (0=segunda … 4=sexta) em que a turma possui contraturno.', verbose_name='Dias de contraturno'),
        ),
    ]
