# Generated by Django 6.0.5 on 2026-08-27 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0014_janela_pre_reserva_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoAutorizado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail institucional')),
                ('nome', models.CharField(blank=True, max_length=150, verbose_name='Nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos_autorizados', to='administrativo.turma')),
            ],
            options={
                'verbose_name': 'Aluno autorizado',
                'verbose_name_plural': 'Alunos autorizados',
                'ordering': ['email'],
            },
        ),
    ]
