# Generated by Django 6.0.5 on 2026-08-24 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0015_alunoautorizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'perfil': 'refeitorio'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presencas_confirmadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
