# Generated by Django 6.0.5 on 2026-06-02 22:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('principal', 'Principal'), ('complemento', 'Complemento'), ('salada', 'Salada'), ('sobremesa', 'Sobremesa')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prato',
                'verbose_name_plural': 'Pratos',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('cafe', 'Café'), ('lanche_manha', 'Lanche da Manhã'), ('almoco', 'Almoço'), ('lanche_tarde', 'Lanche da Tarde'), ('jantar', 'Jantar')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('limite_vagas', models.IntegerField()),
                ('exige_reserva', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Refeição',
                'verbose_name_plural': 'Refeições',
                'ordering': ['data', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='RefeicaoPrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes_vinculadas', to='refeicoes.prato')),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_prato', to='refeicoes.refeicao')),
            ],
            options={
                'verbose_name': 'Prato da refeição',
                'verbose_name_plural': 'Pratos da refeição',
            },
        ),
        migrations.AddField(
            model_name='refeicao',
            name='pratos',
            field=models.ManyToManyField(related_name='refeicoes', through='refeicoes.RefeicaoPrato', to='refeicoes.prato'),
        ),
        migrations.AddConstraint(
            model_name='refeicaoprato',
            constraint=models.UniqueConstraint(fields=('refeicao', 'prato'), name='unique_refeicao_prato'),
        ),
    ]
