# Generated by Django 6.0.5 on 2026-06-02 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refeicoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refeicao',
            name='descricao',
        ),
    ]
