# Generated by Django 6.0.5 on 2026-06-04

from django.db import migrations, models


def _table_exists(schema_editor, table_name):
    return table_name in set(schema_editor.connection.introspection.table_names())


def _column_exists(schema_editor, table_name, column_name):
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(
            cursor, table_name
        )
    return any(col.name == column_name for col in description)


def _column_sql_type(schema_editor, table_name, column_name):
    if schema_editor.connection.vendor != 'postgresql':
        return None
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT data_type
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = %s
              AND column_name = %s
            """,
            [table_name, column_name],
        )
        row = cursor.fetchone()
    return row[0] if row else None


def _is_integer_pk(sql_type):
    return sql_type in ('bigint', 'integer', 'smallint')


def _constraint_exists(schema_editor, table_name, constraint_name):
    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(
            cursor, table_name
        )
    return constraint_name in constraints


def _index_exists(cursor, index_name):
    cursor.execute(
        """
        SELECT 1 FROM pg_indexes
        WHERE schemaname = 'public' AND indexname = %s
        """,
        [index_name],
    )
    return cursor.fetchone() is not None


def _drop_foreign_keys_to(schema_editor, referenced_table, referenced_column='id'):
    qn = schema_editor.quote_name
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT tc.table_name, tc.constraint_name
            FROM information_schema.table_constraints AS tc
            JOIN information_schema.key_column_usage AS kcu
              ON tc.constraint_name = kcu.constraint_name
             AND tc.table_schema = kcu.table_schema
            JOIN information_schema.constraint_column_usage AS ccu
              ON ccu.constraint_name = tc.constraint_name
             AND ccu.table_schema = tc.table_schema
            WHERE tc.constraint_type = 'FOREIGN KEY'
              AND tc.table_schema = 'public'
              AND ccu.table_name = %s
              AND ccu.column_name = %s
            """,
            [referenced_table, referenced_column],
        )
        for table_name, constraint_name in cursor.fetchall():
            cursor.execute(
                f'ALTER TABLE {qn(table_name)} DROP CONSTRAINT {qn(constraint_name)}'
            )


def _drop_reserva_uniques(cursor, qn):
    for name in ('unique_reserva_aluno_refeicao', 'unique_reserva_ativa_aluno_refeicao'):
        if _index_exists(cursor, name):
            cursor.execute(f'DROP INDEX {qn(name)}')
        elif _constraint_exists_on_table(cursor, 'reservas_reserva', name):
            cursor.execute(
                f'ALTER TABLE {qn("reservas_reserva")} DROP CONSTRAINT {qn(name)}'
            )


def _constraint_exists_on_table(cursor, table_name, constraint_name):
    cursor.execute(
        """
        SELECT 1
        FROM information_schema.table_constraints
        WHERE table_schema = 'public'
          AND table_name = %s
          AND constraint_name = %s
        """,
        [table_name, constraint_name],
    )
    return cursor.fetchone() is not None


def _migrate_legacy_bigint_ids(schema_editor):
    """
    Produção aplicou 0001 antiga com BigAutoField em Refeicao (e Reserva).
    O código atual usa UUID — converte antes de criar Prato/RefeicaoPrato.
    """
    if schema_editor.connection.vendor != 'postgresql':
        return

    refeicao_id_type = _column_sql_type(schema_editor, 'refeicoes_refeicao', 'id')
    if not _is_integer_pk(refeicao_id_type):
        return

    qn = schema_editor.quote_name

    with schema_editor.connection.cursor() as cursor:
        _drop_foreign_keys_to(schema_editor, 'refeicoes_refeicao', 'id')

        if _table_exists(schema_editor, 'reservas_reserva'):
            _drop_reserva_uniques(cursor, qn)

        cursor.execute(
            f'ALTER TABLE {qn("refeicoes_refeicao")} ADD COLUMN {qn("id_new")} uuid'
        )
        cursor.execute(
            f'UPDATE {qn("refeicoes_refeicao")} SET {qn("id_new")} = gen_random_uuid()'
        )

        if _table_exists(schema_editor, 'reservas_reserva'):
            refeicao_fk_type = _column_sql_type(
                schema_editor, 'reservas_reserva', 'refeicao_id'
            )
            if _is_integer_pk(refeicao_fk_type):
                cursor.execute(
                    f'ALTER TABLE {qn("reservas_reserva")} '
                    f'ADD COLUMN {qn("refeicao_id_new")} uuid'
                )
                cursor.execute(
                    f"""
                    UPDATE {qn("reservas_reserva")} AS r
                    SET {qn("refeicao_id_new")} = ref.{qn("id_new")}
                    FROM {qn("refeicoes_refeicao")} AS ref
                    WHERE r.{qn("refeicao_id")} = ref.{qn("id")}
                    """
                )
                cursor.execute(
                    f'ALTER TABLE {qn("reservas_reserva")} DROP COLUMN {qn("refeicao_id")}'
                )
                cursor.execute(
                    f'ALTER TABLE {qn("reservas_reserva")} '
                    f'RENAME COLUMN {qn("refeicao_id_new")} TO {qn("refeicao_id")}'
                )

            reserva_id_type = _column_sql_type(schema_editor, 'reservas_reserva', 'id')
            if _is_integer_pk(reserva_id_type):
                _drop_foreign_keys_to(schema_editor, 'reservas_reserva', 'id')
                cursor.execute(
                    f'ALTER TABLE {qn("reservas_reserva")} ADD COLUMN {qn("id_new")} uuid'
                )
                cursor.execute(
                    f'UPDATE {qn("reservas_reserva")} SET {qn("id_new")} = gen_random_uuid()'
                )
                cursor.execute(
                    f'ALTER TABLE {qn("reservas_reserva")} '
                    f'DROP CONSTRAINT {qn("reservas_reserva_pkey")}'
                )
                cursor.execute(
                    f'ALTER TABLE {qn("reservas_reserva")} DROP COLUMN {qn("id")}'
                )
                cursor.execute(
                    f'ALTER TABLE {qn("reservas_reserva")} '
                    f'RENAME COLUMN {qn("id_new")} TO {qn("id")}'
                )
                cursor.execute(
                    f'ALTER TABLE {qn("reservas_reserva")} ADD PRIMARY KEY ({qn("id")})'
                )
                cursor.execute(
                    'DROP SEQUENCE IF EXISTS reservas_reserva_id_seq CASCADE'
                )

        cursor.execute(
            f'ALTER TABLE {qn("refeicoes_refeicao")} '
            f'DROP CONSTRAINT {qn("refeicoes_refeicao_pkey")}'
        )
        cursor.execute(
            f'ALTER TABLE {qn("refeicoes_refeicao")} DROP COLUMN {qn("id")}'
        )
        cursor.execute(
            f'ALTER TABLE {qn("refeicoes_refeicao")} '
            f'RENAME COLUMN {qn("id_new")} TO {qn("id")}'
        )
        cursor.execute(
            f'ALTER TABLE {qn("refeicoes_refeicao")} ADD PRIMARY KEY ({qn("id")})'
        )
        cursor.execute('DROP SEQUENCE IF EXISTS refeicoes_refeicao_id_seq CASCADE')

        if _table_exists(schema_editor, 'reservas_reserva'):
            cursor.execute(
                f"""
                ALTER TABLE {qn("reservas_reserva")}
                ADD CONSTRAINT reservas_reserva_refeicao_id_fk_refeicoes
                FOREIGN KEY ({qn("refeicao_id")})
                REFERENCES {qn("refeicoes_refeicao")} ({qn("id")})
                DEFERRABLE INITIALLY DEFERRED
                """
            )
            if not _index_exists(cursor, 'unique_reserva_ativa_aluno_refeicao'):
                cursor.execute(
                    f"""
                    CREATE UNIQUE INDEX unique_reserva_ativa_aluno_refeicao
                    ON {qn("reservas_reserva")} ({qn("aluno_id")}, {qn("refeicao_id")})
                    WHERE {qn("status")} = 'ativa'
                    """
                )


def _ensure_prato_schema(apps, schema_editor):
    _migrate_legacy_bigint_ids(schema_editor)

    if not _table_exists(schema_editor, 'refeicoes_prato'):
        Prato = apps.get_model('refeicoes', 'Prato')
        RefeicaoPrato = apps.get_model('refeicoes', 'RefeicaoPrato')
        Refeicao = apps.get_model('refeicoes', 'Refeicao')

        schema_editor.create_model(Prato)
        schema_editor.create_model(RefeicaoPrato)

        field = Refeicao._meta.get_field('pratos')
        schema_editor.add_field(Refeicao, field)

        if not _constraint_exists(
            schema_editor, 'refeicoes_refeicaoprato', 'unique_refeicao_prato'
        ):
            schema_editor.add_constraint(
                RefeicaoPrato,
                models.UniqueConstraint(
                    fields=('refeicao', 'prato'),
                    name='unique_refeicao_prato',
                ),
            )

    if _table_exists(schema_editor, 'refeicoes_prato') and not _column_exists(
        schema_editor, 'refeicoes_prato', 'ativo'
    ):
        Prato = apps.get_model('refeicoes', 'Prato')
        ativo_field = models.BooleanField(default=True)
        ativo_field.set_attributes_from_name('ativo')
        schema_editor.add_field(Prato, ativo_field)


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('refeicoes', '0002_remove_refeicao_descricao'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_ensure_prato_schema, _noop_reverse),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='prato',
                    name='ativo',
                    field=models.BooleanField(default=True),
                ),
            ],
        ),
    ]
