# Generated by Django 6.0.5 on 2026-07-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeicoes', '0005_refeicao_chamada_aberta'),
    ]

    operations = [
        migrations.AddField(
            model_name='refeicao',
            name='pre_reservas_disparadas_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pré-reservas disparadas em'),
        ),
    ]
