# Generated by Django 6.0.5 on 2026-07-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refeicoes', '0006_pre_reserva_contraturno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prato',
            name='descricao',
        ),
    ]
