# Generated by Django 6.0.5 on 2026-08-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refeicoes', '0007_remove_prato_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refeicao',
            name='chamada_aberta',
        ),
    ]
