# Generated by Django 6.0.5 on 2026-06-02 22:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('refeicoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='ativa', max_length=20)),
                ('reservado_em', models.DateTimeField(auto_now_add=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'perfil': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='refeicoes.refeicao')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('aluno', 'refeicao'), name='unique_reserva_aluno_refeicao')],
            },
        ),
    ]
