# Generated by Django 6.0.5 on 2026-05-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='turma',
            field=models.CharField(default='refeitorio', max_length=50),
            preserve_default=False,
        ),
    ]
