# Generated by Django 6.0.5 on 2026-06-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('cafe', 'Café'), ('lanche_manha', 'Lanche da Manhã'), ('almoco', 'Almoço'), ('lanche_tarde', 'Lanche da Tarde'), ('jantar', 'Jantar')], max_length=20)),
                ('descricao', models.TextField()),
                ('limite_vagas', models.IntegerField()),
                ('exige_reserva', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Refeição',
                'verbose_name_plural': 'Refeições',
            },
        ),
    ]
