# Generated by Django 6.0.5 on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeicoes', '0002_remove_refeicao_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
