# Generated by Django 6.0.5 on 2026-06-04

import uuid

import django.db.models.deletion
from django.db import migrations, models


def _table_exists(schema_editor, table_name):
    return table_name in set(schema_editor.connection.introspection.table_names())


def _column_exists(schema_editor, table_name, column_name):
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(
            cursor, table_name
        )
    return any(col.name == column_name for col in description)


def _constraint_exists(schema_editor, table_name, constraint_name):
    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(
            cursor, table_name
        )
    return constraint_name in constraints


def _ensure_prato_schema(apps, schema_editor):
    """Bancos que aplicaram 0001 antiga (só Refeicao) não têm tabelas de Prato."""
    if not _table_exists(schema_editor, 'refeicoes_prato'):
        Prato = apps.get_model('refeicoes', 'Prato')
        RefeicaoPrato = apps.get_model('refeicoes', 'RefeicaoPrato')
        Refeicao = apps.get_model('refeicoes', 'Refeicao')

        schema_editor.create_model(Prato)
        schema_editor.create_model(RefeicaoPrato)

        field = Refeicao._meta.get_field('pratos')
        schema_editor.add_field(Refeicao, field)

        if not _constraint_exists(
            schema_editor, 'refeicoes_refeicaoprato', 'unique_refeicao_prato'
        ):
            schema_editor.add_constraint(
                RefeicaoPrato,
                models.UniqueConstraint(
                    fields=('refeicao', 'prato'),
                    name='unique_refeicao_prato',
                ),
            )

    if _table_exists(schema_editor, 'refeicoes_prato') and not _column_exists(
        schema_editor, 'refeicoes_prato', 'ativo'
    ):
        Prato = apps.get_model('refeicoes', 'Prato')
        ativo_field = models.BooleanField(default=True)
        ativo_field.set_attributes_from_name('ativo')
        schema_editor.add_field(Prato, ativo_field)


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('refeicoes', '0002_remove_refeicao_descricao'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_ensure_prato_schema, _noop_reverse),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='prato',
                    name='ativo',
                    field=models.BooleanField(default=True),
                ),
            ],
        ),
    ]
