# Generated by Django 6.0.5 on 2026-06-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeicoes', '0003_prato_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='refeicao',
            name='chamada_finalizada',
            field=models.BooleanField(default=False, verbose_name='Chamada Finalizada'),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='limite_vagas',
            field=models.PositiveIntegerField(),
        ),
    ]
