# Generated by Django 6.0.5 on 2026-08-27 21:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_turma_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoConfirmacaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hash', models.CharField(max_length=128)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('expira_em', models.DateTimeField()),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_confirmacao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
