# Generated by Django 6.0.5 on 2026-06-02 22:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('refeicoes', '0001_initial'),
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigReserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('abertura', models.TimeField()),
                ('encerramento', models.TimeField()),
                ('minutos_cancelamento', models.IntegerField()),
                ('vigente_desde', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(limit_choices_to={'perfil': 'nutricionista'}, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Reserva',
                'verbose_name_plural': 'Configurações de Reserva',
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mensagem', models.CharField(max_length=255)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='refeicoes.refeicao')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compareceu', models.BooleanField()),
                ('confirmado_em', models.DateTimeField(auto_now_add=True)),
                ('confirmado_por', models.ForeignKey(limit_choices_to={'perfil': 'refeitorio'}, on_delete=django.db.models.deletion.CASCADE, related_name='presencas_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presenca', to='reservas.reserva')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aplicado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to=settings.AUTH_USER_MODEL)),
                ('presenca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strike', to='administrativo.presenca')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
