# Generated by Django 6.0.5 on 2026-06-02 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abertura', models.TimeField()),
                ('encerramento', models.TimeField()),
                ('minutos_cancelamento', models.IntegerField()),
                ('vigente_desde', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(limit_choices_to={'perfil': 'nutricionista'}, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Reserva',
                'verbose_name_plural': 'Configurações de Reserva',
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compareceu', models.BooleanField()),
                ('confirmado_em', models.DateTimeField(auto_now_add=True)),
                ('confirmado_por', models.ForeignKey(limit_choices_to={'perfil': 'refeitorio'}, on_delete=django.db.models.deletion.CASCADE, related_name='presencas_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presenca', to='reservas.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to=settings.AUTH_USER_MODEL)),
                ('presenca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strike', to='administrativo.presenca')),
            ],
        ),
    ]
