# Generated by Django 6.0.5 on 2026-06-02 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='Notificacao'),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP TABLE IF EXISTS administrativo_notificacao CASCADE;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
