# Generated by Django 6.0.5 on 2026-06-10 02:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0005_turma_dias_contraturno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRefeicao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('horario_inicio_consumo', models.TimeField(verbose_name='Horário de Início da Refeição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='configreserva',
            options={},
        ),
        migrations.AlterField(
            model_name='configreserva',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='configreserva',
            name='minutos_cancelamento',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='configreserva',
            name='vigente_desde',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='turma',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turno',
            field=models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('noturno', 'Noturno')], default='matutino', max_length=20, verbose_name='Turno'),
        ),
        migrations.CreateModel(
            name='JanelaReserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horario_abertura', models.TimeField(verbose_name='Horário de Abertura (Dia Anterior)')),
                ('horario_fechamento', models.TimeField(verbose_name='Horário de Fechamento (Dia da Refeição)')),
                ('tipo_refeicao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='janela', to='administrativo.tiporefeicao')),
            ],
            options={
                'verbose_name': 'Janela de Reserva',
                'verbose_name_plural': 'Janelas de Reserva',
            },
        ),
    ]
